### ISSUE TITLE
Thousands of Zombie Horses

### ISSUE THREAD

**Issue by ClaudiusMinimus** [p1ut0nium-git/Rough-Mobs-Revamped#39] opened 2020-05-19 02:15 UTC
I am getting thousands of zombie horses spawning in my modpack (2,000-3,000 zombie horses on separate occations). After doing a grep search, the instance of zombie_horse was in your mod roughmobsrevamped-1.15.2-4.1.2.jar.

Attached is the twitch/multimc pack file: [Survival in Chaos-0.30.1.zip](https://github.com/p1ut0nium-git/Rough-Mobs-Revamped/files/4647852/Survival.in.Chaos-0.30.1.zip)

**Comment by p1ut0nium-git** [comment] 2020-05-19 15:52
Thanks for the report. This has to be some issue with another mod conflicting with Rough Mobs. Rough Mobs doesn't spawn entities. It modifies the ones that do. And yes, sometimes that includes adding a zombie horse to zombies that spawn in. So seems like something is overspawning zombies, then they die and leave the horse behind. I'll have a look at your mod back and see if I can figure it out.

**Comment by ClaudiusMinimus** [comment] 2020-05-27 23:42
Have you had any luck finding the issue?

**Comment by Goatle** [comment] 2020-06-14 14:22
Was looking for the source of my hundreds of zombie horses and I think it is this mod as well. For the time being I limited zombie horses in your config file to only spawn at unreasonable heights, so the problem is resolved in a manner.

**Comment by p1ut0nium-git** [comment] 2020-09-29 06:18
Have found no issues. Running the mod on my end causes no extra zombie horses to spawn anywhere. This is what I know so far:

- This mod does not spawn mobs. It replaces the normally spawned ones with "rough" ones when they spawn.
- When a zombie or zombie boss spawns, there is a chance (configurable) it will spawn on a zombie horse.
- It works on my end without issue.

I'm closing this issue for now unless someone can provide me a specific mod that may be causing this issue in conjunction with rough mobs.

**Closed by p1ut0nium-git** 2020-09-29 06:18 UTC
